# Will an error occur if you try to access a list element with an index greater than or equal to the list's length? For example:

# foo = ['a', 'b', 'c']
# print(foo[3])      # will this result in an error?

Yes, this will result in a error since this would be referencing an index that does not exist in this list; this index is "out of range"
